### ISSUE TITLE
Error: Error Code 403 - Client error: (403) Forbidden

### ISSUE THREAD

**Issue by humbertf** [matbmeijer/JirAgileR#6]
Hi. I 'm just trying your example, only changing your domain by mine and other domain  that I also have accesss, and the result is always the same : "Error: Error Code 403 - Client error: (403) Forbidden". Do I have to set up something in the atlassian account? 

library(JirAgileR, quietly = T)
library(knitr, quietly = T)
library(dplyr, quietly = T)

# Save credentials to pass them only one time

save_jira_credentials(domain = "xxxxx" ,
                      username="xxxxx",
                      password = "xxxxx",
)

# Get full list of projects in domain
get_jira_projects() %>% 
  select(key, name)  %>% 
  kable(row.names = F, padding = 0)

**Comment by matbmeijer** [comment]
Hi @humbertf ,
First of all, thank you for using the package.
I cannot replicate your error, as it works for me on all my tests. Ensure that you have access to the JIRA Domain and that your username has the necessary permissions to use the API.

Yet I will propose three different options to find out what the problem is:

1) What results do you obtain when you call `get_jira_credentials()`? Please do not share your direct results, you should get something like this. Notice that you need to use "https:" in the domain:
```r
save_jira_credentials(domain = "https://jira.domain.com/",
                      username = "YOUR_USERNAME",
                      password = "YOUR_PASSWORD")

get_jira_credentials()
```
You should obtain something like this:
|DOMAIN                   |USERNAME      |PASSWORD      |
|:------------------------|:-------------|:-------------|
|https://jira.domain.com/ |YOUR_USERNAME |YOUR_PASSWORD |

If you get these results, the problem does not come from the `save_jira_credentials()`function.

2) Next, let's try to use the `get_jira_projects()`function directly, instead of saving the parameters:
```r
df <- get_jira_projects(domain = "https://jira.domain.com/", username = "YOUR_USERNAME", password = "YOUR_PASSWORD")
```
Let me know if this worked.

3) If it didn't work, you will have to the test the API interactively in your browser. Log into your JIRA domain, and visit the following link (you need to change the domain of the link) and share the results with me, please:
https://jira.domain.com/rest/api/latest/serverInfo

Depending on the server information I will be able to evaluate if the error comes from:
a) Not having the necessary permissions to call the API
b) Other reasons related to server versioning

I hope this helps! Let me know if you have any questions!

**Comment by humbertf** [comment]
Hi @matbmeijer  I already solved the problem.

When I used the API TOKEN instead MY PASSWORD, everything works. I mean, don't use your password use the API TOKEN given by JIRA

![image](https://user-images.githubusercontent.com/41374870/81490065-4a00f280-924b-11ea-9b36-b013d6088e04.png)

save_jira_credentials(domain = "https://jira.domain.com/",
                      username = "YOUR_USERNAME",
                      password = "API TOKEN")

Thanks for your help...

**Comment by matbmeijer** [comment]
Hi @humbertf ,

Thank you for letting me know - normally it should work with your password as it is documented in the JIRA Server documentation:
https://docs.atlassian.com/software/jira/docs/api/REST/8.3.3/

Could it be that you're using JIRA Cloud instead of JIRA server?
I hope you find the package useful.

Kind regards!
